apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sonarqube
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP