apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRole.name }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
      - pods/log
      - services
      - configmaps
      - secrets
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete