apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: jenkins
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jenkins
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: TCP

    - name: jnlp
      port: {{ .Values.service.ports.jnlp.port }}
      targetPort: {{ .Values.service.ports.jnlp.targetPort }}
      protocol: TCP