---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.ports.http.nodePort }}
      protocol: TCP
    - name: jnlp
      port: 50000
      targetPort: 50000
      nodePort: 30500
      protocol: TCP
  selector:
    app: jenkins
  type: NodePort

