---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.namespace }}


---  
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
  annotations:
    kubernetes.io/service-account.name: "{{ .Values.secret.serviceAccountName }}"
type: kubernetes.io/service-account-token


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "namespaces", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "delete"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.clusterRoleBinding.serviceAccountName }}
    namespace: {{ .Values.clusterRoleBinding.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterRoleBinding.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io


