apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30489
      protocol: TCP
    - name: jnlp
      port: 50000
      targetPort: 50000
      nodePort: 30500
      protocol: TCP
  selector:
    app: jenkins
  type: NodePort

