apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins

      # 🔒 Correct security context for Jenkins
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.452.3-lts-jdk21
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pv-claim

      # 🚨 MOST IMPORTANT FIX — PIN TO DATA NODE
      nodeSelector:
        kubernetes.io/hostname: kworker1