namespace: devops-tools

serviceAccount:
  name: jenkins
  namespace: devops-tools

clusterRole:
  name: jenkins-clusterrole

clusterRoleBinding:
  name: jenkins-clusterrolebinding

image:
  name: jenkins/jenkins:lts-jdk21

deployment:
  name: jenkins
  namespace: devops-tools
  replicas: 1

service:
  name: jenkins
  namespace: devops-tools
  type: ClusterIP
  ports:
    http:
      port: 8080
      targetPort: 8080
    jnlp:
      port: 50000
      targetPort: 50000

controller:
  serviceAccount:
    create: false
    name: jenkins