namespace:
  name: devops-tools

storageClass:
  name: local-storage

persistentVolume:
  enabled: false
  name: jenkins-pv
  capacity: 5Gi
  hostPath: /mnt/data1/jenkins
  storageClassName: local-storage

persistentVolumeClaim:
  enabled: true
  name: jenkins-pv-claim
  namespace: devops-tools
  storage: 5Gi
  storageClassName: local-storage

serviceAccount:
  name: jenkins
  namespace: devops-tools

rbac:
  clusterRoleName: jenkins-clusterrole
  clusterRoleBindingName: jenkins-clusterrolebinding

service:
  name: jenkins
  namespace: devops-tools
  type: ClusterIP
  ports:
    http:
      port: 8080
      targetPort: 8080
    jnlp:
      port: 50000
      targetPort: 50000

deployment:
  name: jenkins
  namespace: devops-tools
  replicas: 1

image:
  name: jenkins/jenkins:lts-jdk21

controller:
  serviceAccount:
    create: false
    name: jenkins